# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('COMPLETE', 'Complete'), ('NOT_STARTED', 'Not Started'), ('IN_PROGRES', 'In Progres')], default='NOT_STARTED', max_length=12)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=9)),
            ],
        ),
    ]
