# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='token',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
