# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170615_0634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('user_id',)},
        ),
    ]
